### ISSUE TITLE
what a phobos skid

### ISSUE THREAD

**Issue by 3jq** [Gopro336/OyVey_Rewrite-BUILDABLE_SRC#8]
just a phobos skid, don't download it

**Comment by Sixtieth** [comment]
go fuck yourself

**Comment by phobologicalt** [comment]
might be a phobos skid but you can use it with konas so alot of people use it

**Comment by amogusman01** [comment]
are you brain damaged?

**Comment by master7720** [comment]
> are you brain damaged?

he has a fitmc video as a pfp so he might be

**Comment by phobologicalt** [comment]
> > are you brain damaged?
> 
> he has a fitmc video as a pfp so he might be

litterally posted this comment like 6 months ago, who are you

**Comment by master7720** [comment]
> > > are you brain damaged?
> > 
> > 
> > he has a fitmc video as a pfp so he might be
> 
> litterally posted this comment like 6 months ago, who are you

me?

**Comment by master7720** [comment]
> just a phobos skid, don't download it

oyvey is more compatible with sum other clients if i remembered right thats why ppl use it

**Comment by phobologicalt** [comment]
> > > > are you brain damaged?
> > > 
> > > 
> > > he has a fitmc video as a pfp so he might be
> > 
> > 
> > litterally posted this comment like 6 months ago, who are you
> 
> me?

nah just the person im replying to

**Comment by phobologicalt** [comment]
yes you idiot

**Comment by master7720** [comment]
> are you brain damaged?

he kinda is "might be a phobos skid" xD

**Comment by phobological** [comment]
> 

your the braindamaged one here
